services:
  redis:
    image: redis:latest
    ports:
      - 6380:6379
    volumes:
      - redisdata:/data
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
  redisdata:
